### ISSUE TITLE
[FEAT] 회원가입시 이메일 인증 구현

### ISSUE THREAD

**Issue by YunYeoKyeong99** [PLAC-Planning-Your-Activities/plac-server#19]
### New Feature
- 회원가입시 '여섯자리 숫자' 인증번호를 메일로 전송
- 인증번호를 통한 이메일 인증

### Detail
- 이메일 인증 요청 형태
POST /verify_code
{
    "email": "user@example.com",
    "enteredCode": "123456"
}

**Comment by YunYeoKyeong99** [comment]
### TODO
- [ ] 구글 이메일 계정 만들기
- [ ] 이메일 전송 로직 만들기
- [ ] 이메일 기반 회원가입 완료시 인증 메일 전송
- [ ] 인증 메일 재전송
- [ ] 인증번호를 통한 인증
