### ISSUE TITLE
[FEAT] 배포

### ISSUE THREAD

**Issue by YunYeoKyeong99** [PLAC-Planning-Your-Activities/plac-server#22]
### New Feature
- 배포

### Detail
- GithubAction으로 도커 이미지를 빌드하고 도커 허브에 이미지를 업로드한다.
- GithubAcion으로 EC2 서버의 배포 스크립트를 실행시킨다.

### TODO
- [x] Dockerfile 작성
- [x] 설정파일에서 환경변수 분리
- [x] GithubAction 스크립트 작성
- [x] 배포 스크립트 작성
- [x] EC2 도커 설치
- [x] EC2 NginX 설치 및 설정 수정
- [x] EC2 SSL/TLS 인증서 발급 및 적용

### ISSUE
- [ ] 도커 이미지 라벨 제대로 안붙음
