### ISSUE TITLE
프로젝트 구조 변경 & 기능 축소

### ISSUE THREAD

**Issue by Jungsu-lilly** [PLAC-Planning-Your-Activities/plac-server#30]
## Description 📝
* 계층구조 에서, 도메인 구조로 프로젝트를 변경합니다.
* 새로운 버전에 따른 기능을 변경, 축소합니다. (place 관련 리뷰와 댓글이 사라졌습니다.)
* Service 가 interface -> class 로 변경됩니다.

## TODO ✅
- [ ] 프로젝트의 구조를 계층 -> 도메인 위주로 변경하기
- [ ] Controller, Service, Repository 단으로 나누었던 계층을, 도메인 위주로 변경합니다.
- [ ] 테스트 시 문제 없이 실행 되는지 확인
