### ISSUE TITLE
플랜(Plan) 관련 로직 구현

### ISSUE THREAD

**Issue by Jungsu-lilly** [PLAC-Planning-Your-Activities/plac-server#34]
### 플랜 관련된 로직을 구현합니다.
* 장소를 추가해 플랜을 생성하는 기능을 구현합니다.
* 커뮤니티에 플랜을 공유하고, 태그를 통해 필터링할 수 있습니다.
* 플랜 저장(스크랩), 좋아요 누르기

<br>

## TODO ✅
- [ ] 플랜 생성 구현
- [ ] 플랜에 태그를 지정해, 커뮤니티에 공유하는 기능
- [ ] 태글 통해 플랜을 필터링 검색
- [ ] 플랜 저장(스크랩)
- [ ] 플랜 좋아요 누르기
